### ISSUE TITLE
Was able to install

### ISSUE THREAD

**Issue by dsandstrom** [abe33/uninstallable#1]
Just to confirm.  I was able to install with Atom's settings-view, but not able to install with `apm` directly.

**Comment by abe33** [comment]
So you are the one! :smile: 

I created this package to test my PR on the atom/settings-view package in real conditions.
To follow the progress on this issue take a look at atom/settings-view#377

**Comment by dsandstrom** [comment]
Well when something says it can't be done, I must try.  I noticed this bug, but never got around to trying to fix it: https://discuss.atom.io/t/how-to-require-an-atom-version-in-package-json/13212.  Thanks.

**Comment by Ajedi32** [comment]
Wait, so you created a package named "uninstallable" to test your fix to atom/settings-view#377, and someone installed it and created a bug report to tell you it didn't work? :laughing: Hahaha. That's hilarious. :smile:

**Comment by dsandstrom** [comment]
I just wanted to confirm that I could install this package, I knew it was a dummy package.
